First pull request for the test-guru project
sochnevl/test-guru pull request #1
Opened 2023-09-30 15:36 UTC by sochnevl

2023-10-01 10:05 UTC, VidgarVii requested changes

2023-10-01 10:05 UTC, VidgarVii commented on README.md
> +прохождения тестов. Возможные методы для сохранения результатов и просмотра их истории.
Достаточно было указать названия сущностей)

2023-10-01 10:05 UTC, VidgarVii commented on app/controllers/pages_controller.rb
> +class PagesController < ApplicationController
`html` файлы целиком статические
их будет оптимальнее отдать вообще в обход рельсового приложения (так будет работать быстрее, да и рельсам с этими файлами делать то нечего)
для этого их достаточно поместить в директорию `public`

роуты при этом не нужны и контроллеры тоже
(путь к файлу внутри директории `public` должен соответствовать пути, по которому этот файл должен быть доступен)

2023-10-01 10:05 UTC, VidgarVii commented on app/views/pages/author.html.erb
> +<p><a href="https://github.com/sochnevl">Профиль GitHub автора</a></p>
ссылки на сторонние ресурсы правильно открывать в новой вкладке и хорошо бы добавить опцию rel=nofollow rel=noopener. Так клиента сохраним и поискового робота дальше не пустим

2023-10-01 10:05 UTC, VidgarVii commented on config/application.rb
> +    config.i18n.default_locale = :ru
чтобы не было ошибок в системе, надо еще добавить файл конфигураций в папку config/locales ru.yml. Содержание почти аналогичное как en.yml

2023-10-01 10:05 UTC, VidgarVii commented on config/initializers/version.rb
> +  VERSION = '1.0.0'
ПО еще не готово к выходу на продакшен. По этому мы можем определить только минорную версию.

2023-10-02 13:41 UTC, sochnevl reviewed
Исправлены замечания наставника

2023-10-03 05:42 UTC, VidgarVii requested changes

2023-10-03 05:42 UTC, VidgarVii commented on README.md
не хватает Категории

2023-10-03 05:42 UTC, VidgarVii commented on config/initializers/version.rb
> +  VERSION = '0.1'
0.1.0

2023-10-03 05:42 UTC, VidgarVii commented on public/about.html
> +</html>
в конце файла надо отставлять 1 пустую строчку. Это указатель на конец файла. Сейчас система думает, что происходит обрыв файла. Даже гитхаб ругается. No new lina at end of file. Многие компиляторы тут выдадут ошибку. Руби частично компилируемый язык. И такой разрыв легко проглотит. Но в реальных проектах это как красная тряпка для быка. Так что тренируем дисциплину и больше такого не совершаем! В руби за чистоту кода!

2023-10-03 15:14 UTC, sochnevl reviewed
Исправлены замечания наставника

2023-10-05 13:00 UTC, merged